# Generated by Django 5.1.6 on 2025-04-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hostpasswordhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostpasswordhistory',
            old_name='password',
            new_name='root_password',
        ),
    ]
